version: '3.11'

services:
  db:
    image: postgres:15.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
      
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  web:
    build: .
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - redis
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web


volumes:
  static_value:
  media_value:
